### ISSUE TITLE
Radio Buttons not working correctly

### ISSUE THREAD

**Issue by beanthemoonman** [Kaybass/CSI-319-Project-1#2]
When a radio button is used for a question it cannot be selected again until another radio button is highlighted

Radio buttons are reset in quiz activity with

> `for(int i = 0; i < 4; ++i){
>                             mAnswers[i].setText(mQuestions[mQuestionIndex].getAnswer(i));
>                             mAnswers[i].setChecked(false);
>                         }`

**Comment by joeListro** [comment]
Fixed using method:

`(RadioGroup).clearCheck();`

**Comment by beanthemoonman** [comment]
another one
